sequenceDiagram
    participant G as Greeter
    participant D as greetd

    G->>D: create_session(username)
    D->>G: auth_message(secret)
    G->>D: post_auth_message_response(password)
    D->>G: error(auth_error)
    G->>D: cancel_session
    D->>G: success
    Note over G, D: Back to idle, can retry
